# Generated by Django 5.0.2 on 2024-03-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantimage",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
